#!/usr/bin/env python3
"""
Creates the statistics and performance table in LaTeX.
"""
import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
import re
import sys
import textwrap
from typing import TextIO

from google.cloud import storage
from google.cloud.storage.bucket import Bucket
from tqdm import tqdm
import yaml


@dataclass(frozen=True)
class Application:
    display_name: str  # Display name in the table; may use LaTeX.
    identifier: str  # How the application is identified in result paths.
    run_folder_fmt: str  # e.g., "{app}-{controller}-{action}-{suffix}"
    handlers: tuple["Handler", ...]  # Handlers in the application.
    policy_folder_fmt: str = "{app}-{suffix}-policy"


@dataclass(frozen=True)
class Handler:
    controller: str
    action: str
    custom_display_name: str = None  # Optional; may use LaTeX.

    @property
    def display_name(self) -> str:
        if self.custom_display_name is not None:
            return self.custom_display_name
        return f"{self.controller.capitalize()}\\#{self.action}"


APPS: tuple[Application, ...] = (
    Application(
        display_name=r"\diaspora",
        identifier="diaspora",
        run_folder_fmt="{app}-{controller}-{action}-2r-{suffix}",
        handlers=(
            Handler(controller="people", action="stream"),
            Handler(controller="posts", action="show"),
            Handler(controller="people", action="show"),
            Handler(controller="notifications", action="index"),
            Handler(controller="conversations", action="index"),
            Handler(controller="comments", action="index"),
        ),
    ),
    Application(
        display_name="Autolab",
        identifier="autolab",
        run_folder_fmt="{app}-{controller}-{action}-2r-{suffix}",
        handlers=(
            Handler(controller="assessments", action="gradesheet"),
            Handler(controller="assessments", action="index"),
            Handler(controller="submissions", action="download"),
            Handler(controller="courses", action="index"),
            Handler(controller="metrics", action="pending", custom_display_name="Metrics\\#getNumPending"),
        ),
    ),
    Application(
        display_name="The Odin Project",
        identifier="theodinproject",
        run_folder_fmt="{app}-{controller}_{action}-{suffix}",
        handlers=(
            Handler(controller="lessons", action="show"),
            Handler(controller="courses", action="show"),
            Handler(controller="project-submissions", action="index",
                    custom_display_name="ProjectSubmissions\\#index"),
            Handler(controller="users", action="show"),
            Handler(controller="paths", action="index"),
            Handler(controller="sitemap", action="index"),
        ),
    )
)


class ValidateSuffixes(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None) -> None:
        try:
            d = yaml.safe_load(values)
        except yaml.YAMLError as e:
            parser.error(f"Invalid YAML: {e}")

        if not isinstance(d, dict):
            raise argparse.ArgumentError(self, "Suffixes must be a YAML dictionary.")

        for app in APPS:
            if app.identifier not in d:
                raise argparse.ArgumentError(self, f"Missing suffix for application '{app.identifier}'.")
        setattr(namespace, self.dest, d)


class ValidateOutputDirectory(argparse.Action):
    def __call__(self, parser, namespace, path, option_string=None) -> None:
        assert isinstance(path, Path)
        if not path.is_dir():
            raise argparse.ArgumentError(self, "Output directory does not exist.")
        setattr(namespace, self.dest, path)


def print_table_header(f: TextIO, command_line: str) -> None:
    print(f"% Generated by {command_line}", file=f)
    print(textwrap.dedent(r"""\begin{NiceTabular}{
        l % handler
        r % #paths
        r % #CQs start
        @{\hskip 0.5\tabcolsep}c@{\hskip 0.5\tabcolsep}
        @{\hskip 0pt}r % #CQs end
        r % #views
        l % #final views
        r % Exploration time
        r % CQ simplification time
        r % View pruning time (per handler)
        r % View pruning time (together)
        }
        \toprule
        & \Block{1-6}{\textbf{Statistics}} & & & & & & \Block{1-4}{\textbf{Running Time}} & & & \\
        \cmidrule(lr){2-7} \cmidrule(lr){8-11}
        Handler & \#Paths & \Block{1-3}{\#Cond.~Queries} & & & \Block{1-2}{\#SQL Views} & & Explore & Simplify & Prune & Final Prune \\
        """).strip(), file=f)


def read_float(bucket: Bucket, path: str) -> float:
    return float(bucket.get_blob(path).download_as_text())


def count_views(bucket: Bucket, path: str) -> int:
    views = bucket.get_blob(path).download_as_text()
    return sum(1 for line in views.splitlines() if line.startswith("SELECT"))


def format_time_s(seconds: float) -> str:
    if seconds < 1:
        raise ValueError("Not supported: <1 second.")
    if seconds < 60:
        return r"\SI{%.0f}{\second}" % seconds
    if seconds < 3600:
        return r"\SI{%.0f}{\minute}" % (seconds / 60)
    return r"\SI{%.1f}{\hour}" % (seconds / 3600)


def print_app(f: TextIO, app: Application, bucket: Bucket, suffix: str) -> int:
    """
    Prints the statistics and performance of an application.
    :param f: the file to write to
    :param app: the application
    :param bucket: the Google Cloud storage bucket
    :param suffix: the suffix for the application's run
    :return: the number of final views
    """
    policy_folder = app.policy_folder_fmt.format(app=app.identifier, suffix=suffix)
    final_prune_dur_s = read_float(bucket, f"{policy_folder}/remove-subsumed-time-sec.txt")
    num_final_views = count_views(bucket, f"{policy_folder}/all-minimized.sql")

    print(r"\midrule", file=f)
    print(r"\textbf{%s} & & & & & & & & & & %s \\" % (app.display_name, format_time_s(final_prune_dur_s)), file=f)

    for i, handler in enumerate(tqdm(app.handlers, desc=f"Handlers of {app.identifier}")):
        folder = app.run_folder_fmt.format(app=app.identifier, controller=handler.controller, action=handler.action,
                                           suffix=suffix)

        runs_blob = bucket.get_blob(
            f"{folder}/metrics/edu.berkeley.cs.netsys.policy_extraction.cmdline.ExploreExecutionsImpl.runs.csv")
        runs = list(csv.DictReader(runs_blob.download_as_text().splitlines()))
        explore_timestamps_s = [int(row["t"]) for row in runs]
        explore_dur_s = max(explore_timestamps_s) - min(explore_timestamps_s)
        num_paths = max(int(row["count"]) for row in runs)

        gen_cqs_log: str = bucket.get_blob(f"{folder}/annotated-paths/generate-cqs.log").download_as_text()
        num_cqs_start = int(re.search(r"Converted to (\d+) conditioned queries\.", gen_cqs_log).group(1))
        num_cqs_end = int(
            re.search(r"There are (\d+) conditioned queries after removing subsumed\.", gen_cqs_log).group(1)
        )

        num_minimized_views = count_views(bucket, f"{folder}/annotated-paths/views-minimized.sql")

        simplify_dur_s = read_float(bucket, f"{folder}/annotated-paths/post-processing-time-sec.txt")
        prune_dur_s = read_float(bucket, f"{folder}/annotated-paths/remove-subsumed-time-sec.txt")

        f.write(r"\quad\texttt{%s} & \num{%d} & \num{%d} & $\to$ & \num{%d} & \num{%d} &" %
                (handler.display_name, num_paths, num_cqs_start, num_cqs_end, num_minimized_views))
        if i == 0:
            f.write(r"\Block{%d-1}{$\to$ \num{%d}}" % (len(app.handlers), num_final_views))
        print(r"& %s & %s & %s & \\" %
              (format_time_s(explore_dur_s), format_time_s(simplify_dur_s), format_time_s(prune_dur_s)), file=f)

    return num_final_views


def print_table_footer(f: TextIO) -> None:
    print(r"\bottomrule", file=f)
    # Draw right curly braces.
    curr_row = 3
    for app in APPS:
        num_handlers = len(app.handlers)
        print(r"\CodeAfter\SubMatrix.{%d-6}{%d-6}\}" % (curr_row + 1, curr_row + num_handlers), file=f)
        curr_row += 1 + num_handlers  # Skip the application header row and all handler rows.
    print(r"\end{NiceTabular}", file=f)


def main() -> None:
    parser = argparse.ArgumentParser(description="Create the statistics and performance table in LaTeX.")
    parser.add_argument("gcloud_bucket", type=str,
                        help="Google Cloud storage bucket where experiment results are stored.")
    parser.add_argument("suffixes", type=str, action=ValidateSuffixes,
                        help="Suffixes for each application's run; expressed as a YAML dictionary mapping application "
                             "identifiers to suffixes.")
    parser.add_argument("output_dir", type=Path, action=ValidateOutputDirectory,
                        help="Output directory for the LaTeX table and macro definitions.")
    args = parser.parse_args()

    with (args.output_dir / "table.tex").open("w") as f:
        print_table_header(f, command_line=" ".join(sys.argv))

        storage_client = storage.Client()
        bucket = storage_client.get_bucket(args.gcloud_bucket)
        app2num_final_views: dict[Application, int] = {}
        for app in tqdm(APPS, desc="Applications"):
            suffix = args.suffixes[app.identifier]
            num_final_views = print_app(f, app, bucket, suffix)
            app2num_final_views[app] = num_final_views

        print_table_footer(f)

    with (args.output_dir / "stats-macros.tex").open("w") as f:
        # Define some macros for the final-view counts.
        for app, num_final_views in app2num_final_views.items():
            print(r"\newcommand{\%sFinalViews}{\num{%d}\xspace}" % (app.identifier, num_final_views), file=f)


if __name__ == "__main__":
    main()
